baseURL: http://blog.bermuda.de
languageCode: de-de
title: Bermuda Blog
paginate: 10
theme: binario
# googleAnalytics
Author:
  name: Nils Bokermann
#  bio: |-
#    Ich bin als freiberuflicher IT-Consultant im Java Umfeld tätig. Darüber hinaus berate ich meine Kunden in Architektur- und Methodik-Fragen.
# avatar =

markup:
  tableOfContents:
    startLevel: 0
    endLevel: 3
params:
  dateFormat: "2.01.2006"
  authorbox: true

  entry:
    meta:
      - date
      - categories
    toc: true # Enable Table of Contents
    tocOpen: true # Open Table of Contents block. Optional
  Social:
    email: nils.bokermann+blog@bermuda.de
    xing: Nils_Bokermann
    twitter: sanddorn
    linkedin: nils-bokermann-3267826
    github: sanddorn
    gitlab: nils.bokermann

taxonomies:
  category: "categories"
#  tag: "tags"
#  series: "series"

menu:
  icon:
    - url: https://github.com/sanddorn
      name: "github"
      weigh: 1
#    - url: https://gitlab.com/sanddorn
#      name: "gitlab"
#      weigh: 1
    - url: https://tiwtter.com/sanddorn
      name: "twitter"
      weigh: 1
    - url: https://xing.com/profile/Nils_Bokermann
      name: "xing"
      weigh: 1
    - url: https://www.linkedin.com/in/nils-bokermann-3267826
      name: "linkedin"
      weigh: 1
