baseURL: http://blog.bermuda.de
languageCode: de-de
title: Bermuda Blog
theme: erblog

params:
  author: Nils Bokermann
  bio: |-
    <p class="markdown-body p">Ich bin als freiberuflicher IT-Consultant im Java Umfeld tätig. Darüber hinaus berate ich meine Kunden in Architektur- und Methodik-Fragen.</p>
    <p class="markdown-body p">Eines meiner Hobbies ist es Hype getriebene Entscheidungen infrage zu stellen und mich so oft zum Advocatus Diaboli zu machen.</p>
  description: |-
    Java, Security, Verantwortung, Freelancer


taxonomies:
  category: "categories"
#  tag: "tags"
#  series: "series"

menu:
  icon:
    - url: https://github.com/sanddorn
      name: "github"
      weigh: 1
#    - url: https://gitlab.com/sanddorn
#      name: "gitlab"
#      weigh: 1
    - url: https://tiwtter.com/sanddorn
      name: "twitter"
      weigh: 1
    - url: https://xing.com/profile/Nils_Bokermann
      name: "xing"
      weigh: 1
    - url: https://www.linkedin.com/in/nils-bokermann-3267826
      name: "linkedin"
      weigh: 1
