baseURL: https://blog.bermuda.de
languageCode: de-de
defaultContentLanguage: de
title: Bermuda Blog
paginate: 10
theme: binario
# googleAnalytics
Author:
  name: Nils Bokermann
#  avatar: /img/avatar.png
#  bio: |-
#    Ich bin als freiberuflicher IT-Consultant im Java Umfeld tätig. Darüber hinaus berate ich meine Kunden in Architektur- und Methodik-Fragen.
# avatar =

markup:
  tableOfContents:
    startLevel: 0
    endLevel: 3
params:
  dateFormat: "2.01.2006"
  authorbox: true
  customCSS:
    - css/blog.css
    - https://cdn.jsdelivr.net/npm/@algolia/algoliasearch-netlify-frontend@1/dist/algoliasearchNetlify.css
  customJS:
    - https://cdn.jsdelivr.net/npm/@algolia/algoliasearch-netlify-frontend@1/dist/algoliasearchNetlify.js
    - js/algolia.js
  description:
    "Der Blog von Nils Bokermann"

  entry:
    meta:
      - date
      - categories
    toc: true # Enable Table of Contents
    tocOpen: true # Open Table of Contents block. Optional
  Social:
    email: nils.bokermann+blog@bermuda.de
    xing: Nils_Bokermann
    twitter: sanddorn
    linkedin: nils-bokermann-3267826
    github: sanddorn
    gitlab: nils.bokermann
  Share:
    facebook: true
    twitter: true
    linkedin: true
    xing: true
  breadcrumb:
    enable: false
    homeText: "Bermuda Blog"

outputFormats:
  MANIFEST:
    mediaType: "application/json"
    basename: "manifest"
    isPlainText: true
    notAlternative: true
outputs:
  home:
    - "HTML"
    - "RSS"
    - "MANIFEST"


taxonomies:
  category: "categories"
#  tag: "tags"
#  series: "series"
